"""empty message

Revision ID: 00eb2529b76f
Revises: 3c690ff8b1f6
Create Date: 2016-06-19 14:22:58.054221

"""

# revision identifiers, used by Alembic.
revision = '00eb2529b76f'
down_revision = '3c690ff8b1f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_criteria_value')
    op.drop_constraint(None, 'user_created_text_mapper', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_created_text_mapper', 'search_criteria_value', ['search_criteria_value'], ['id'])
    op.create_table('search_criteria_value',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=256), nullable=True),
    sa.Column('search_criteria', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['search_criteria'], [u'search_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
