"""empty message

Revision ID: 380607bbf115
Revises: None
Create Date: 2016-06-19 03:22:09.814184

"""

# revision identifiers, used by Alembic.
revision = '380607bbf115'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atr_averagebill',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_city',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_features',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_kitchens',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_metro',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_recommend',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('atr_types',
    sa.Column('id_atr', sa.Integer(), nullable=False),
    sa.Column('text_atr', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id_atr')
    )
    op.create_table('rest_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rest', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('billMin', sa.String(length=64), nullable=True),
    sa.Column('billMax', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('photourl', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rest_info_id_rest'), 'rest_info', ['id_rest'], unique=False)
    op.create_table('search_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quick_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_rest', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Integer(), nullable=True),
    sa.Column('metro', sa.Integer(), nullable=True),
    sa.Column('bill', sa.Integer(), nullable=True),
    sa.Column('features', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('cuisine', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill'], ['atr_averagebill.id_atr'], ),
    sa.ForeignKeyConstraint(['city'], ['atr_city.id_atr'], ),
    sa.ForeignKeyConstraint(['cuisine'], ['atr_kitchens.id_atr'], ),
    sa.ForeignKeyConstraint(['features'], ['atr_features.id_atr'], ),
    sa.ForeignKeyConstraint(['id_rest'], ['rest_info.id_rest'], ),
    sa.ForeignKeyConstraint(['metro'], ['atr_metro.id_atr'], ),
    sa.ForeignKeyConstraint(['purpose'], ['atr_recommend.id_atr'], ),
    sa.ForeignKeyConstraint(['type'], ['atr_types.id_atr'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_criteria_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('search_criteria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_criteria'], ['search_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_created_text_mapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_criteria', sa.Integer(), nullable=True),
    sa.Column('user_text', sa.String(length=256), nullable=True),
    sa.Column('search_criteria_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['search_criteria'], ['search_criteria.id'], ),
    sa.ForeignKeyConstraint(['search_criteria_value'], ['search_criteria_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_text_mapper_user_text'), 'user_created_text_mapper', ['user_text'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_text_mapper_user_text'), table_name='user_created_text_mapper')
    op.drop_table('user_created_text_mapper')
    op.drop_table('search_criteria_value')
    op.drop_table('quick_search')
    op.drop_table('search_criteria')
    op.drop_index(op.f('ix_rest_info_id_rest'), table_name='rest_info')
    op.drop_table('rest_info')
    op.drop_table('atr_types')
    op.drop_table('atr_recommend')
    op.drop_table('atr_metro')
    op.drop_table('atr_kitchens')
    op.drop_table('atr_features')
    op.drop_table('atr_city')
    op.drop_table('atr_averagebill')
    ### end Alembic commands ###
